# loki-redis.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: registry.cn-guangzhou.aliyuncs.com/kubernetes-default/redis:6.0.20
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 6379
      # - name: redis-exporter # 它只会提供监控指标数据，主应用的metrics
      #   image: oliver006/redis_exporter:latest
      #   resources:
      #     requests:
      #       cpu: 100m
      #       memory: 100Mi
      #     limits:
      #       cpu: 100m
      #       memory: 100Mi
      #   ports:
      #   - containerPort: 9121
---
kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: monitoring
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: prom
    port: 9121
    targetPort: 9121
  type: ClusterIP
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: redis
#   namespace: monitoring
# spec:
#   endpoints:
#   - port: prom
#   selector:
#     matchLabels:
#       app: redis