apiVersion: v1
kind: Secret
metadata:
  name: loki-config
  namespace: monitoring
  labels:
    helm.sh/chart: loki-distributed-0.71.2
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: "2.8.4"
    app.kubernetes.io/managed-by: Helm
stringData:
  config.yaml: |
    auth_enabled: false

    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
      graceful_shutdown_timeout: 30s
      http_server_read_timeout: 1m
      http_server_write_timeout: 1m
      http_server_idle_timeout: 2m
      log_format: json
      log_level: info

    # 通用配置
    common:
      compactor_address: http://loki-loki-distributed-compactor:3100

    compactor:
      # 下载文件进行压缩的工作目录。
      working_directory: /var/loki/compactor
      # 用于存储boltdb文件的共享存储。
      shared_store: s3
      # 重新运行压缩操作的间隔。
      compaction_interval: 10m
      # 应用/执行保留的间隔时间。0表示与压缩间隔相同的间隔运行。如果非零，则应始终是压缩间隔的倍数。
      apply_retention_interval: 20m
      # 每个压缩周期运行的最大删除请求数。
      delete_batch_size: 10000
      # 用于删除块的工作进程总数。
      retention_delete_worker_count: 10000
      # 并行压缩的最大表数。在增加此值时，请确保为压缩器分配了足够的磁盘空间，以能够存储和压缩尽可能多的表。
      max_compaction_parallelism: 1
      compactor_ring:
        kvstore:
          store: memberlist
      shared_store_key_prefix: compactor_index/

    distributor:
      ring:
        kvstore:
          store: memberlist
      rate_store:
        # 向ingester流API发出的并发请求的最大数量
        max_request_parallelism: 2000
        # 分发器从ingester更新当前流速的间隔
        stream_rate_update_interval: 5s
        # 更新速率时，分发器与任何给定的ingester之间的通信超时
        ingester_request_timeout: 3s

    frontend:
      # 每个前端租户的最大未完成请求数；超过此数会返回 HTTP 429 错误。
      max_outstanding_per_tenant: 1000000
      # 压缩 HTTP 响应。
      compress_responses: true
      # 查询持续时间超过指定时间的查询将被记录日志。设置为 0 以禁用该功能。
      log_queries_longer_than: 5s
      # 用于尾部代理的查询器的 URL
      tail_proxy_url: http://loki-loki-distributed-querier:3100
    frontend_worker:
      frontend_address: loki-loki-distributed-query-frontend-headless:9095
      # 每个查询前端或查询调度器同时处理的查询数。
      parallelism: 100

    ingester:
      # 块的目标“压缩”大小（以字节为单位）。这是一个期望的大小，而不是精确的大小。
      chunk_block_size: 262144
      # 用于压缩块的算法。（none、gzip、lz4-64k、snappy、lz4-256k、lz4-1M、lz4、flate、zstd）
      chunk_encoding: snappy
      # 如果块未达到最大块大小，则块在没有更新的情况下在内存中停留多长时间后进行刷新。
      chunk_idle_period: 1h
      # 块在刷新后在内存中保留的持续时间。
      chunk_retain_period: 30s
      # 内存中时间序列块的最大持续时间。如果一个时间序列运行时间超过此值，当前块将被刷新到存储中，并创建一个新的块。
      max_chunk_age: 1h
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          # 写入和读取的ingesters数量。
          replication_factor: 1
      max_transfer_retries: 0
      wal:
        # 在重放期间WAL可以使用的最大内存大小。达到此限制后，它将在继续之前将数据刷新到存储中。可以应用单位后缀（KB、MB、GB）。
        replay_memory_ceiling: 1GB
        # 存储和/或从中恢复WAL数据的目录。
        dir: wal

    limits_config:
      # 强制每个样本都有一个指标名称。
      enforce_metric_name: false
      # 每个流每秒的最大字节速率。
      per_stream_rate_limit: 512MB
      # 每个流的最大突发字节数
      per_stream_rate_limit_burst: 1024MB
      # 每个用户的摄取速率限制，以每秒样本大小为单位。单位为MB。
      ingestion_rate_mb: 1000
      # 每个用户允许的摄取突发大小（以样本大小为单位）。单位为MB。即使在“global”策略下，突发大小也是指每个分发器的本地速率限制器，并且应该设置为单个推送请求中预期的最大日志大小。
      ingestion_burst_size_mb: 2000
      # 每个标签集的标签名称的最大数量。
      max_label_names_per_series: 50
      max_cache_freshness_per_query: 10m
      # 是否拒绝旧样本。  
      reject_old_samples: true
      # 拒绝之前的样本的最大接受时间。
      reject_old_samples_max_age: 1w
      # 每个用户每个接收器的活跃流的最大数量，设置为0以禁用。
      max_streams_per_user: 0
      # 全局设置,每个集群中每个用户的活跃流的最大数量，设置为0以禁用。
      max_global_streams_per_user: 0
      # 单个查询中可以获取的最大块数。
      max_chunks_per_query: 2000000
      # 每个查询的最大流匹配器数量。
      max_streams_matchers_per_query: 100000
      # 查询返回的最大日志条目数。
      max_entries_limit_per_query: 5000000
      # 限制查询返回的唯一标签集的最大数量。当达到限制时，将返回错误。
      max_query_series: 10000
      # 按时间间隔拆分查询并并行执行。值为0禁用按时间拆分。
      split_queries_by_interval: 30m
      join_members:
      - loki-loki-distributed-memberlist

    query_range:
      align_queries_with_step: true
      cache_results: true
      max_retries: 5
      results_cache:
        cache:
          redis:
            endpoint: redis:6379
            expiration: 1h

    ruler:
      alertmanager_url: alertmanager-main.monitoring.svc:9093
      storage:
        local:
          directory: /etc/loki/rules
        type: local
      rule_path: /tmp/loki/scratch
      external_labels:
        cluster: local
      evaluation_interval: 2m
      enable_alertmanager_v2: true
      notification_timeout: 30s
      enable_api: true
      rule_path: /loki/rules
      ring:
        kvstore:
          store: memberlist

    schema_config:
      configs:
      - from: "2022-07-11"
        index:
          period: 24h
          prefix: loki_index_
        object_store: s3
        schema: v12
        store: boltdb-shipper

    runtime_config:
      file: /var/loki-distributed-runtime/runtime.yaml

    # 配置如何缓存块以及在将它们保存到后端存储之前等待多长时间
    chunk_store_config:
      chunk_cache_config:
        redis:
          endpoint: redis:6379
          expiration: 1h
      write_dedupe_cache_config:
        redis:
          endpoint: redis:6379
          expiration: 1h
      max_look_back_period: 0s

    storage_config:
      aws:
        endpoint: minio.logging.svc.cluster.local:9000
        insecure: true
        bucketnames: loki-data
        access_key_id: minio
        secret_access_key: minio123
        s3forcepathstyle: true
        http_config:
          idle_conn_timeout: 90s
          response_header_timeout: 0s
          insecure_skip_verify: true
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_ttl: 12h
        shared_store: s3
        cache_location: /var/loki/cache
      filesystem:
        directory: /var/loki/chunks
      # 每批获取的最大块数。
      max_chunk_batch_size: 1000
      # 并行获取块的最大数量。
      max_parallel_get_chunk: 5000
      # 活动索引条目的缓存有效期。不应超过-ingester.max-chunk-idle
      index_cache_validity: 30m
      # 缓存配置
      index_queries_cache_config:
        redis:
          endpoint: redis:6379
          expiration: 1h
      hedging:
        at: 0 
        max_per_second: 20  
        up_to: 3

    #定义索引网关服务器将以哪种模式运行（默认为“simple”）。它支持两种模式：
    # - 'simple'：一个索引网关服务器实例负责处理、存储和返回所有租户的所有索引的请求。
    # - 'ring'：一个索引网关服务器实例负责一部分租户，而不是所有租户。    
    index_gateway:
      mode: simple
      ring:
        kvstore:
          store: memberlist
      # 为每个租户分配多少个索引网关实例。
      replication_factor: 1

    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
type: Opaque