apiVersion: v1
kind: Secret
metadata:
  name: loki-config
  namespace: monitoring
  labels:
    helm.sh/chart: loki-simple-scalable-1.8.11
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: "2.8.2"
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  config.yaml: |
    auth_enabled: false
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
      graceful_shutdown_timeout: 30s
      http_server_read_timeout: 1m
      http_server_write_timeout: 1m
      http_server_idle_timeout: 2m
      log_format: json
      log_level: info
    common:
      path_prefix: /var/loki
      replication_factor: 1
      storage:
        s3:
          access_key_id: minio
          secret_access_key: minio123
          bucketnames: chunks
          endpoint: minio-service:9000
          insecure: true
          s3forcepathstyle: true
          http_config:
            idle_conn_timeout: 90s
            response_header_timeout: 0s
            insecure_skip_verify: true
    limits_config:
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 1w
      max_streams_matchers_per_query: 50000
      max_entries_limit_per_query: 50000
      max_query_series: 2000
      split_queries_by_interval: 30m
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 1h
      max_chunk_age: 1h
      chunk_target_size: 2048576
      chunk_retain_period: 30s
      max_transfer_retries: 0
      wal:
        enabled: true
        replay_memory_ceiling: 1GB
    memberlist:
      join_members:
      - loki-memberlist
    # frontend:
    #   log_queries_longer_than: 0
    #   max_outstanding_per_tenant: 5000
    # querier:
    #   query_ingesters_within: 3h
    #   max_concurrent: 10
    # query_scheduler:
    #   max_outstanding_requests_per_tenant: 1000
    #   scheduler_ring:
    #     kvstore:
    #       store: memberlist
    query_range:
      align_queries_with_step: true
      results_cache:
        cache:
          redis:
            endpoint: redis:6379
            expiration: 1h
      cache_results: true
    ruler:
      storage:
        s3:
          bucketnames: ruler
      alertmanager_url: alertmanager-main.monitoring.svc:9093
      external_labels:
        cluster: other_label
      evaluation_interval: 2m
      enable_alertmanager_v2: true
      notification_timeout: 30s
      enable_api: true
      rule_path: /tmp/rules
      ring:
        kvstore:
          store: memberlist
    schema_config:
      configs:
      - from: "2022-07-11"
        index:
          period: 24h
          prefix: loki_index_
        object_store: s3
        schema: v12
        store: boltdb-shipper
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/index_cache
        cache_ttl: 12h
        shared_store: s3
      max_chunk_batch_size: 50
      max_parallel_get_chunk: 500
      index_cache_validity: 30m
      index_queries_cache_config:
        redis:
          endpoint: redis:6379
          expiration: 1h
      hedging:
        at: 0 
        max_per_second: 20  
        up_to: 3
    chunk_store_config:
      chunk_cache_config:
        redis:
          endpoint: redis:6379
          expiration: 1h
      write_dedupe_cache_config:
        redis:
          endpoint: redis:6379
          expiration: 1h
    compactor:
      working_directory: /var/loki/compactor
      shared_store: s3
      compaction_interval: 5m
      shared_store_key_prefix: compactor_index/