{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": {}
   },
   {
    "name": "Level",
    "query": {}
   },
   { "name": "Query" }
  ]
 },
 "panels": [
  {
   "title": "日志级别(0)  Emergency 60m统计 ",
   "type": "stat",
   "description": "设备致命的异常，系统已经无法恢复正常，必须重启设备。如程序异常导致设备重启，内存的使用被检测出错误等。",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({Level=\"0\"}[60m]))",
     "legendFormat": "{{Host}}"
    }
   ]
  },
  {
   "title": "日志级别(1)  Alert 60m统计 ",
   "type": "stat",
   "description": "设备重大的异常，需要立即采取措施。如设备内存占用率达到极限等。",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({Host=\"$Host\"}[60m] |~ \"\\\\/1\\\\/\"))",
     "legendFormat": "{{Host}}"
    }
   ]
  },
  {
   "title": "日志级别(2) Critical 60m 统计 ",
   "type": "stat",
   "description": "设备重大的异常，需要采取措施进行处理或原因分析。如设备内存占用率超过低界线，温度超过低温告警线，BFD探测出设备不可达，检测出错误的消息（消息是由本设备内部生成）等。",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({Host=\"$Host\"}[60m] |~ \"\\\\/2\\\\/\"))",
     "legendFormat": "{{Host}}"
    }
   ]
  },
  {
   "title": "日志60m增长速率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate({Level=\"$Level\"}[60m])) by (Host)"
    }
   ]
  },
  {
   "title": "各办公室对应级别的日志合计数量 60m",
   "type": "table",
   "description": "按照全局变量下 <Level> 变量进行统计 60m内 对于的日志合计数量",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({Level=\"$Level\"}[1h])) by (Host)"
    }
   ]
  },
  {
   "title": "日志级别(3) Error 60m统计",
   "type": "stat",
   "description": "错误的操作或设备的异常流程，不会影响后续业务，但是需要关注和原因分析。如错误指令，用户密码错误，检测出错误协议报文（报文是由其他设备获得）。",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({Host=\"$Host\"}[60m] |~ \"\\\\/3\\\\/\"))",
     "legendFormat": "{{Host}}"
    }
   ]
  },
  {
   "title": "日志级别(4) Warning 60m统计",
   "type": "stat",
   "description": "设备的异常运转的异常点，可能引起业务故障的流程，需要引起注意。如关闭路由进程，BFD探测的一次报文丢失，检测出错误协议报文等。",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({Host=\"$Host\"}[60m] |~ \"\\\\/4\\\\/\"))",
     "legendFormat": "{{Host}}"
    }
   ]
  },
  {
   "title": "日志级别(5) Notice 60m 统计",
   "type": "stat",
   "description": "用于设备正常运转的关键操作信息。如执行shutdown命令，邻居发现，协议状态机的正常跳转等。",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({Host=\"$Host\"}[60m] |~ \"\\\\/5\\\\/\"))",
     "legendFormat": "{{Host}}"
    }
   ]
  },
  {
   "title": "全局日志检索",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"usglogs\"} |~ \"\\\\/$Level\\\\/\" |= \"$Host\" |= \"$Query\" | logfmt"
    }
   ]
  }
 ]
}