apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail
  namespace: default
  labels:
    helm.sh/chart: promtail-6.11.2
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/version: "2.8.2"
    app.kubernetes.io/managed-by: Helm
data:
  promtail.yaml: |
    server:
      log_level: info
      log_format: json
      http_listen_port: 3101
      http_server_idle_timeout: 120s
      http_server_write_timeout: 30s
      http_server_read_timeout: 30s
      graceful_shutdown_timeout: 30s
      profiling_enabled: false

    clients:
      - url: http://loki-gateway/loki/api/v1/push
        batchwait: 1s
        batchsize: 1048576
        drop_rate_limited_batches: true
        external_labels:
          cluster: debian
        timeout: 30s

    positions:
      filename: /run/promtail/positions.yaml
      sync_period: 10s
      ignore_invalid_yaml: false

    scrape_configs:
      - job_name: syslog
        pipeline_stages:
        - match:
            selector: '{job="syslog"}'
            stages:
            - regex:
                expression: '^(?P<Time>\S+\s+\d{1,2}\s\d{2}:\d{2}:\d{2}) (?P<Hostname>\S+) (?P<Module>\w+)(?P<MSG>.*)'
            - labels:
                Hostname:
                Module:
        static_configs:
        - targets:
            - localhost
          labels:
            job: syslog
            __path__: /var/log/messages

      - job_name: kubernetes-pods
        pipeline_stages:
          - cri: {}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_controller_name
            regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
            action: replace
            target_label: __tmp_controller_name
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_name
              - __meta_kubernetes_pod_label_app
              - __tmp_controller_name
              - __meta_kubernetes_pod_name
            regex: ^;*([^;]+)(;.*)?$
            action: replace
            target_label: app
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_instance
              - __meta_kubernetes_pod_label_instance
            regex: ^;*([^;]+)(;.*)?$
            action: replace
            target_label: instance
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_component
              - __meta_kubernetes_pod_label_component
            regex: ^;*([^;]+)(;.*)?$
            action: replace
            target_label: component
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_node_name
            target_label: node_name
          - action: replace
            source_labels:
            - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            replacement: $1
            separator: /
            source_labels:
            - namespace
            - app
            target_label: job
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_container_name
            target_label: container
          - action: replace
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
            - __meta_kubernetes_pod_uid
            - __meta_kubernetes_pod_container_name
            target_label: __path__
          - action: replace
            regex: true/(.*)
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
            - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
            - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
            - __meta_kubernetes_pod_container_name
            target_label: __path__
    limits_config:
      readline_rate_enabled: false
      readline_rate_drop: true
      readline_rate: 10000
      readline_burst: 20000
      max_streams: 0
      max_line_size: 0
      max_line_size_truncate: false
    target_config:
      sync_period: "10s"
    tracing:
      enable: false
