apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: promealert-pvc
  namespace: vm-single
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 20Gi